update=среда, 14. фебруар 2018. 12:19:14 CET
version=1
last_client=kicad
[pcbnew]
version=1
LastNetListRead=
UseCmpFile=1
PadDrill=0.600000000000
PadDrillOvalY=0.600000000000
PadSizeH=1.500000000000
PadSizeV=1.500000000000
PcbTextSizeV=1.500000000000
PcbTextSizeH=1.500000000000
PcbTextThickness=0.300000000000
ModuleTextSizeV=1.000000000000
ModuleTextSizeH=1.000000000000
ModuleTextSizeThickness=0.150000000000
SolderMaskClearance=0.000000000000
SolderMaskMinWidth=0.000000000000
DrawSegmentWidth=0.200000000000
BoardOutlineThickness=0.100000000000
ModuleOutlineThickness=0.150000000000
[cvpcb]
version=1
NetIExt=net
[general]
version=1
[eeschema]
version=1
LibDir=
[eeschema/libraries]
LibName1=Optoboard-rescue
LibName2=power
LibName3=device
LibName4=switches
LibName5=relays
LibName6=motors
LibName7=transistors
LibName8=conn
LibName9=linear
LibName10=regul
LibName11=74xx
LibName12=cmos4000
LibName13=adc-dac
LibName14=memory
LibName15=xilinx
LibName16=microcontrollers
LibName17=dsp
LibName18=microchip
LibName19=analog_switches
LibName20=motorola
LibName21=texas
LibName22=intel
LibName23=audio
LibName24=interface
LibName25=digital-audio
LibName26=philips
LibName27=display
LibName28=cypress
LibName29=siliconi
LibName30=opto
LibName31=atmel
LibName32=contrib
LibName33=valves
LibName34=/home/silardg/Development/Robotics/Hardware/Kicad libraries/SparkFun-Kicad-Libraries-master/User-Submitted
LibName35=/home/silardg/Development/Robotics/Hardware/Kicad libraries/SparkFun-Kicad-Libraries-master/Teensy_3_and_LC_Series_Boards_v1.1
LibName36=/home/silardg/Development/Robotics/Hardware/Kicad libraries/SparkFun-Kicad-Libraries-master/SparkFun-Sensors
LibName37=/home/silardg/Development/Robotics/Hardware/Kicad libraries/SparkFun-Kicad-Libraries-master/SparkFun-RF
LibName38=/home/silardg/Development/Robotics/Hardware/Kicad libraries/SparkFun-Kicad-Libraries-master/SparkFun-Retired
LibName39=/home/silardg/Development/Robotics/Hardware/Kicad libraries/SparkFun-Kicad-Libraries-master/SparkFun-Resistors
LibName40=/home/silardg/Development/Robotics/Hardware/Kicad libraries/SparkFun-Kicad-Libraries-master/SparkFun-PowerIC
LibName41=/home/silardg/Development/Robotics/Hardware/Kicad libraries/SparkFun-Kicad-Libraries-master/SparkFun-Passives
LibName42=/home/silardg/Development/Robotics/Hardware/Kicad libraries/SparkFun-Kicad-Libraries-master/SparkFun-LED
LibName43=/home/silardg/Development/Robotics/Hardware/Kicad libraries/SparkFun-Kicad-Libraries-master/SparkFun-FreqCtrl
LibName44=/home/silardg/Development/Robotics/Hardware/Kicad libraries/SparkFun-Kicad-Libraries-master/SparkFun-Electromechanical
LibName45=/home/silardg/Development/Robotics/Hardware/Kicad libraries/SparkFun-Kicad-Libraries-master/SparkFun-Displays
LibName46=/home/silardg/Development/Robotics/Hardware/Kicad libraries/SparkFun-Kicad-Libraries-master/SparkFun-DiscreteSemi
LibName47=/home/silardg/Development/Robotics/Hardware/Kicad libraries/SparkFun-Kicad-Libraries-master/SparkFun-DigitalIC
LibName48=/home/silardg/Development/Robotics/Hardware/Kicad libraries/SparkFun-Kicad-Libraries-master/SparkFun-Connectors
LibName49=/home/silardg/Development/Robotics/Hardware/Kicad libraries/SparkFun-Kicad-Libraries-master/SparkFun-Capacitors
LibName50=/home/silardg/Development/Robotics/Hardware/Kicad libraries/SparkFun-Kicad-Libraries-master/SparkFun-Boards
LibName51=/home/silardg/Development/Robotics/Hardware/Kicad libraries/SparkFun-Kicad-Libraries-master/SparkFun-AnalogIC
LibName52=/home/silardg/Development/Robotics/Hardware/Kicad libraries/SparkFun-Kicad-Libraries-master/SparkFun-Aesthetics
LibName53=/home/silardg/Development/Robotics/Hardware/Kicad libraries/SparkFun-Kicad-Libraries-master/LilyPad-Wearables
LibName54=/home/silardg/Development/Robotics/Hardware/Kicad libraries/SparkFun-Kicad-Libraries-master/GeekAmmo
LibName55=/home/silardg/Development/Robotics/Hardware/Kicad libraries/SparkFun-Kicad-Libraries-master/adafruit
LibName56=74xgxx
LibName57=ac-dc
LibName58=actel
LibName59=allegro
LibName60=Altera
LibName61=analog_devices
LibName62=battery_management
LibName63=bbd
LibName64=bosch
LibName65=brooktre
LibName66=cmos_ieee
LibName67=dc-dc
LibName68=diode
LibName69=elec-unifil
LibName70=ESD_Protection
LibName71=ftdi
LibName72=gennum
LibName73=graphic
LibName74=hc11
LibName75=ir
LibName76=Lattice
LibName77=leds
LibName78=logo
LibName79=maxim
LibName80=mechanical
LibName81=microchip_dspic33dsc
LibName82=microchip_pic10mcu
LibName83=microchip_pic12mcu
LibName84=microchip_pic16mcu
LibName85=microchip_pic18mcu
LibName86=microchip_pic24mcu
LibName87=microchip_pic32mcu
LibName88=modules
LibName89=motor_drivers
LibName90=msp430
LibName91=nordicsemi
LibName92=nxp
LibName93=nxp_armmcu
LibName94=onsemi
LibName95=Oscillators
LibName96=powerint
LibName97=Power_Management
LibName98=pspice
LibName99=references
LibName100=rfcom
LibName101=sensors
LibName102=silabs
LibName103=stm8
LibName104=stm32
LibName105=supertex
LibName106=transf
LibName107=triac_thyristor
LibName108=ttl_ieee
LibName109=video
LibName110=wiznet
LibName111=Worldsemi
LibName112=Xicor
LibName113=zetex
LibName114=Zilog
[schematic_editor]
version=1
PageLayoutDescrFile=
PlotDirectoryName=
SubpartIdSeparator=0
SubpartFirstId=65
NetFmtName=Pcbnew
SpiceForceRefPrefix=0
SpiceUseNetNumbers=0
LabSize=60
